apiVersion: v1
kind: ConfigMap
metadata:
  name: nexusops-config
  namespace: nexusops
data:
  SPRING_PROFILES_ACTIVE: "prod"
  NEXUSOPS_API_BASE_URL: "https://api.nexusops.com"
  NEXUSOPS_CORS_ALLOWED_ORIGINS: "https://nexusops.com"
  LOG_LEVEL_ROOT: "INFO"
  LOG_LEVEL_COM_NEXUSOPS: "INFO"