apiVersion: v1
kind: Secret
metadata:
  name: nexusops-secrets
  namespace: nexusops
type: Opaque
stringData:
  db-host: ""
  db-port: "5432"
  db-name: "nexusops"
  db-user: ""
  db-password: ""
  redis-host: ""
  redis-port: "6379"
  redis-password: ""
  jwt-private-key: ""
  jwt-public-key: ""
  mail-host: ""
  mail-port: "587"
  mail-user: ""
  mail-password: ""